<font color=Green>
    
# **3.6 Fechas con pandas**

</font>

### Pandas también incluye sus propias funciones para trabajar con fechas.

In [1]:
import numpy as np
import pandas as pd
import datetime

## <font color=#003d5c>_.to_datetime()_ </font>

In [2]:
fecha = pd.to_datetime('24th April, 2020')

print(fecha)
print(type(fecha))

2020-04-24 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [3]:
fecha.hour, fecha.minute, fecha.second

(0, 0, 0)

## <font color=#003d5c>_.to_timedelta()_ </font>
### Esta función nos permite calcular los días antes o después de una fecha determinada.

In [4]:
fecha = datetime.datetime.now()

print(fecha)

2022-08-22 14:57:00.839185

### La fecha del día siguiente

In [5]:
#pasando argumentos en este caso aumenta cuatro dias a la varible fecha
print('La fecha de hoy es: ', fecha)

print('Y la fecha en 4 días será: ', fecha + pd.to_timedelta(4,unit='D'))

La fecha de hoy es:  2022-08-22 14:57:00.839185
Y la fecha en 4 días será:  2022-08-26 14:57:00.839185

## <font color=#003d5c>_.date_range()_ </font>
### Este método nos permite generar un rango de fechas.

In [6]:
#paramentros el 1 para start 2 end y 3 su frecuecia (x dia)
fechas_inicio = pd.date_range(start='24/4/2020', end='24/5/2020', freq='D')
fechas_inicio

DatetimeIndex(['2020-04-24', '2020-04-25', '2020-04-26', '2020-04-27',
               '2020-04-28', '2020-04-29', '2020-04-30', '2020-05-01',
               '2020-05-02', '2020-05-03', '2020-05-04', '2020-05-05',
               '2020-05-06', '2020-05-07', '2020-05-08', '2020-05-09',
               '2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13',
               '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17',
               '2020-05-18', '2020-05-19', '2020-05-20', '2020-05-21',
               '2020-05-22', '2020-05-23', '2020-05-24'],
              dtype='datetime64[ns]', freq='D')

In [7]:
fechas_fin = pd.date_range(start='24/5/2020', end='24/6/2020', freq='D')
fechas_fin

DatetimeIndex(['2020-05-24', '2020-05-25', '2020-05-26', '2020-05-27',
               '2020-05-28', '2020-05-29', '2020-05-30', '2020-05-31',
               '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
               '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08',
               '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12',
               '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16',
               '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20',
               '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24'],
              dtype='datetime64[ns]', freq='D')

In [9]:
lista_equis = []

for i in range(15):
    lista_equis.append(np.random.randint(2))


df = pd.DataFrame()

df['Inicio_campaña'] = fechas_inicio[:15]
df['Fin_campaña'] = fechas_fin[:15]
df['Target'] = lista_equis

df

   Inicio_campaña Fin_campaña  Target
0      2020-04-24  2020-05-24       1
1      2020-04-25  2020-05-25       0
2      2020-04-26  2020-05-26       1
3      2020-04-27  2020-05-27       1
4      2020-04-28  2020-05-28       0
5      2020-04-29  2020-05-29       1
6      2020-04-30  2020-05-30       1
7      2020-05-01  2020-05-31       0
8      2020-05-02  2020-06-01       0
9      2020-05-03  2020-06-02       0
10     2020-05-04  2020-06-03       0
11     2020-05-05  2020-06-04       0
12     2020-05-06  2020-06-05       0
13     2020-05-07  2020-06-06       1
14     2020-05-08  2020-06-07       1

In [10]:
df['Día de inicio'] = df['Inicio_campaña'].dt.day


df['Mes de inicio'] = df['Inicio_campaña'].dt.month


df['Año de inicio'] = df['Inicio_campaña'].dt.year


df['Hora_inicio'] = df['Inicio_campaña'].dt.hour


df['Minuto_inicio'] = df['Inicio_campaña'].dt.minute


df['Segundo_inicio'] = df['Inicio_campaña'].dt.second


df['Nombre del día de inicio'] = df['Inicio_campaña'].dt.weekday


df['Semana del año de inicio'] = df['Inicio_campaña'].dt.week


df['Duración'] = df['Fin_campaña']-df['Inicio_campaña']

/tmp/ipykernel_10163/1215509156.py:22: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  df['Semana del año de inicio'] = df['Inicio_campaña'].dt.week

In [11]:
df.columns = ['Inicio_campaña', 'Fin_campaña', 'Target','Día de inicio','Mes de inicio','Año de inicio','Hora_inicio',
              'Minuto_inicio','Segundo_inicio','Día de la semana del inicio','Semana del año de inicio','Duración']

In [12]:
df

,Inicio_campaña,Fin_campaña,Target,Día de inicio,Mes de inicio,Año de inicio,Hora_inicio,Minuto_inicio,Segundo_inicio,Día de la semana del inicio,Semana del año de inicio,Duración
0,2020-04-24,2020-05-24,1,24,4,2020,0,0,0,4,17,30 days
1,2020-04-25,2020-05-25,0,25,4,2020,0,0,0,5,17,30 days
2,2020-04-26,2020-05-26,1,26,4,2020,0,0,0,6,17,30 days
3,2020-04-27,2020-05-27,1,27,4,2020,0,0,0,0,18,30 days
4,2020-04-28,2020-05-28,0,28,4,2020,0,0,0,1,18,30 days
5,2020-04-29,2020-05-29,1,29,4,2020,0,0,0,2,18,30 days
6,2020-04-30,2020-05-30,1,30,4,2020,0,0,0,3,18,30 days
7,2020-05-01,2020-05-31,0,1,5,2020,0,0,0,4,18,30 days
8,2020-05-02,2020-06-01,0,2,5,2020,0,0,0,5,18,30 days
9,2020-05-03,2020-06-02,0,3,5,2020,0,0,0,6,18,30 days
10,2020-05-04,2020-06-03,0,4,5,2020,0,0,0,0,19,30 days
11,2020-05-05,2020-06-04,0,5,5,2020,0,0,0,1,19,30 days
12,2020-05-06,2020-06-05,0,6,5,2020,0,0,0,2,19,30 days
13,2020-05-07,2020-06-06,1,7,5,2020,0,0,0,3,19,30 days
14,2020-05-08,2020-06-07,1,8,5,2020,0,0,0,4,19,30 days

In [13]:
from datetime import timedelta

df['Días de duración'] = df['Duración']/timedelta(days=1)

df['Minutos de duración'] = df['Duración']/timedelta(minutes=1)

df['Segundos de duración'] = df['Duración']/timedelta(seconds=1)

df

,Inicio_campaña,Fin_campaña,Target,Día de inicio,Mes de inicio,Año de inicio,Hora_inicio,Minuto_inicio,Segundo_inicio,Día de la semana del inicio,Semana del año de inicio,Duración,Días de duración,Minutos de duración,Segundos de duración
0,2020-04-24,2020-05-24,1,24,4,2020,0,0,0,4,17,30 days,30.0,43200.0,2592000.0
1,2020-04-25,2020-05-25,0,25,4,2020,0,0,0,5,17,30 days,30.0,43200.0,2592000.0
2,2020-04-26,2020-05-26,1,26,4,2020,0,0,0,6,17,30 days,30.0,43200.0,2592000.0
3,2020-04-27,2020-05-27,1,27,4,2020,0,0,0,0,18,30 days,30.0,43200.0,2592000.0
4,2020-04-28,2020-05-28,0,28,4,2020,0,0,0,1,18,30 days,30.0,43200.0,2592000.0
5,2020-04-29,2020-05-29,1,29,4,2020,0,0,0,2,18,30 days,30.0,43200.0,2592000.0
6,2020-04-30,2020-05-30,1,30,4,2020,0,0,0,3,18,30 days,30.0,43200.0,2592000.0
7,2020-05-01,2020-05-31,0,1,5,2020,0,0,0,4,18,30 days,30.0,43200.0,2592000.0
8,2020-05-02,2020-06-01,0,2,5,2020,0,0,0,5,18,30 days,30.0,43200.0,2592000.0
9,2020-05-03,2020-06-02,0,3,5,2020,0,0,0,6,18,30 days,30.0,43200.0,2592000.0
10,2020-05-04,2020-06-03,0,4,5,2020,0,0,0,0,19,30 days,30.0,43200.0,2592000.0
11,2020-05-05,2020-06-04,0,5,5,2020,0,0,0,1,19,30 days,30.0,43200.0,2592000.0
12,2020-05-06,2020-06-05,0,6,5,2020,0,0,0,2,19,30 days,30.0,43200.0,2592000.0
13,2020-05-07,2020-06-06,1,7,5,2020,0,0,0,3,19,30 days,30.0,43200.0,2592000.0
14,2020-05-08,2020-06-07,1,8,5,2020,0,0,0,4,19,30 days,30.0,43200.0,2592000.0